<?php
/**
 * OrganizationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API PartyManagement
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrganizationTest Class Doc Comment
 *
 * @category    Class
 * @description Organization
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrganizationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Organization"
     */
    public function testOrganization()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "href"
     */
    public function testPropertyHref()
    {
    }

    /**
     * Test attribute "is_legal_entity"
     */
    public function testPropertyIsLegalEntity()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "exists_during"
     */
    public function testPropertyExistsDuring()
    {
    }

    /**
     * Test attribute "trading_name"
     */
    public function testPropertyTradingName()
    {
    }

    /**
     * Test attribute "name_type"
     */
    public function testPropertyNameType()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "other_name"
     */
    public function testPropertyOtherName()
    {
    }

    /**
     * Test attribute "characteristic"
     */
    public function testPropertyCharacteristic()
    {
    }

    /**
     * Test attribute "organization_identification"
     */
    public function testPropertyOrganizationIdentification()
    {
    }

    /**
     * Test attribute "external_reference"
     */
    public function testPropertyExternalReference()
    {
    }

    /**
     * Test attribute "related_party"
     */
    public function testPropertyRelatedParty()
    {
    }

    /**
     * Test attribute "organization_parent_relationship"
     */
    public function testPropertyOrganizationParentRelationship()
    {
    }

    /**
     * Test attribute "organization_child_relationship"
     */
    public function testPropertyOrganizationChildRelationship()
    {
    }

    /**
     * Test attribute "contact_medium"
     */
    public function testPropertyContactMedium()
    {
    }
}
