<?php
/**
 * IndividualApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API PartyManagement
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * IndividualApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IndividualApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for individualCreate
     *
     * individualCreate.
     *
     */
    public function testIndividualCreate()
    {
    }

    /**
     * Test case for individualDelete
     *
     * individualDelete.
     *
     */
    public function testIndividualDelete()
    {
    }

    /**
     * Test case for individualFind
     *
     * individualFind.
     *
     */
    public function testIndividualFind()
    {
    }

    /**
     * Test case for individualGet
     *
     * individualGet.
     *
     */
    public function testIndividualGet()
    {
    }

    /**
     * Test case for individualPatch
     *
     * individualPatch.
     *
     */
    public function testIndividualPatch()
    {
    }

    /**
     * Test case for individualUpdate
     *
     * individualUpdate.
     *
     */
    public function testIndividualUpdate()
    {
    }
}
