<?php
/**
 * OrganizationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API PartyManagement
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OrganizationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrganizationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for organizationCreate
     *
     * organizationCreate.
     *
     */
    public function testOrganizationCreate()
    {
    }

    /**
     * Test case for organizationFind
     *
     * organizationFind.
     *
     */
    public function testOrganizationFind()
    {
    }

    /**
     * Test case for organizationGet
     *
     * organizationGet.
     *
     */
    public function testOrganizationGet()
    {
    }

    /**
     * Test case for organizationPatch
     *
     * organizationPatch.
     *
     */
    public function testOrganizationPatch()
    {
    }

    /**
     * Test case for organizationUpdate
     *
     * organizationUpdate.
     *
     */
    public function testOrganizationUpdate()
    {
    }
}
